name: Build ShadowJar

on:
push:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v4

  - run: chmod +x gradlew

  - uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Build
    run: ./gradlew shadowJar


  - name: Find jars
    run: find . -type f -name "*.jar"


  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: jars
      path: |
        ./**/*.jar
```
